INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Titian', 'After Many a Summer Dies the Swan', 'Schoen, Schoen and Schoen', 'Sports', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Rembrandt', 'The Cricket on the Hearth', 'Anderson Inc', 'Ranching', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Da Vinci', 'Rosemary Sutcliff', 'Kassulke, Kassulke and Kassulke', 'Packaging and Containers', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Warhol', 'In Death Ground', 'Hand, Hand and Hand', 'Think Tanks', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Rubens', 'Time of our Darkness', 'Lakin Inc', 'Package / Freight Delivery', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('El Greco', 'The Wings of the Dove', 'Sanford-Sanford', 'Farming', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Monet', 'The Torment of Others', 'Conroy, Conroy and Conroy', 'Tobacco', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Bernini', 'Precious Bane', 'Lynch-Lynch', 'Photography', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Michelangelo', 'Absalom, Absalom!', 'Nikolaus-Nikolaus', 'Glass, Ceramics & Concrete', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Kahlo', 'Arms and the Man', 'Strosin and Sons', 'Real Estate', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Warhol', 'Wildfire at Midnight', 'Homenick-Homenick', 'Construction', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Ansel Adams', 'All the Kings Men', 'Bauch and Sons', 'Glass, Ceramics & Concrete', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Renoir', 'An Evil Cradling', 'Torp LLC', 'Venture Capital & Private Equity', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Joan Miro', 'Eyeless in Gaza', 'Terry-Terry', 'Writing and Editing', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Monet', 'Tirra Lirra by the River', 'Hodkiewicz, Hodkiewicz and Hodkiewicz', 'Luxury Goods & Jewelry', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Matisse', 'To Sail Beyond the Sunset', 'Paucek-Paucek', 'Investment Banking', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Donatello', 'A Handful of Dust', 'Kirlin, Kirlin and Kirlin', 'International Trade and Development', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Ansel Adams', 'The Parliament of Man', 'Mitchell-Mitchell', 'Nonprofit Organization Management', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Da Vinci', 'In Death Ground', 'Grant-Grant', 'Industrial Automation', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Klimt', 'The Man Within', 'Eichmann-Eichmann', 'Hospital & Health Care', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Pissarro', 'The Golden Bowl', 'Raynor Inc', 'Public Safety', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Donatello', 'No Longer at Ease', 'Hirthe, Hirthe and Hirthe', 'Online Media', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Donatello', 'Of Human Bondage', 'Welch-Welch', 'Government Administration', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Monet', 'Taming a Sea Horse', 'Johns-Johns', 'Computer Software', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Rubens', 'A Darkling Plain', 'Davis and Sons', 'Transportationg / Trucking / Railroad', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Klimt', 'Nectar in a Sieve', 'Legros, Legros and Legros', 'Financial Services', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Warhol', 'The Sun Also Rises', 'Kuhic, Kuhic and Kuhic', 'Hospital & Health Care', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Joan Miro', 'Oh! To be in England', 'Wunsch Inc', 'Business Supplies and Equipment', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Chagall', 'A Time to Kill', 'Okuneva-Okuneva', 'Computer & Network Security', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Pollock', 'Waiting for the Barbarians', 'Satterfield, Satterfield and Satterfield', 'Ranching', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Durer', 'The Moving Toyshop', 'Schmitt-Schmitt', 'Public Policy', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Seurat', 'A Summer Bird-Cage', 'Ryan-Ryan', 'Writing and Editing', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Munch', 'As I Lay Dying', 'Medhurst-Medhurst', 'Medical Practice', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Diego Rivera', 'Postern of Fate', 'Smitham, Smitham and Smitham', 'Mechanical or Industrial Engineering', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Pissarro', 'Beneath the Bleeding', 'Pfannerstill, Pfannerstill and Pfannerstill', 'Computer Networking', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Dali', 'Tender Is the Night', 'Corwin Group', 'Apparel & Fashion', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Titian', 'An Evil Cradling', 'Mante, Mante and Mante', 'Consumer Services', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Rubens', 'The House of Mirth', 'Mills-Mills', 'Printing', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Michelangelo', 'The Moving Finger', 'Smith, Smith and Smith', 'Paper & Forest Products', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Renoir', 'Nine Coaches Waiting', 'Emard Group', 'Think Tanks', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Diego Rivera', 'The Moon by Night', 'Gleason, Gleason and Gleason', 'Management Consulting', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Pissarro', 'A Farewell to Arms', 'Stamm-Stamm', 'Shipbuilding', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Rembrandt', 'In Death Ground', 'Flatley-Flatley', 'Restaurants', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Klimt', 'Things Fall Apart', 'Greenholt, Greenholt and Greenholt', 'Real Estate', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Dali', 'Bloods a Rover', 'Schultz, Schultz and Schultz', 'Capital Markets', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Escher', 'Precious Bane', 'Wisozk-Wisozk', 'Automotive', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Vincent', 'Ring of Bright Water', 'Pfannerstill Group', 'Photography', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Joan Miro', 'For a Breath I Tarry', 'Bergstrom LLC', 'Farming', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Manet', 'The Way Through the Woods', 'Blanda-Blanda', 'Market Research', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Dali', 'This Side of Paradise', 'Thompson, Thompson and Thompson', 'Architecture & Planning', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Rembrandt', 'Butter In a Lordly Dish', 'Pfannerstill, Pfannerstill and Pfannerstill', 'Human Resources', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Winslow Homer', 'Tiger! Tiger!', 'Swaniawski-Swaniawski', 'Oil & Energy', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Seurat', 'Rosemary Sutcliff', 'Christiansen and Sons', 'Farming', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Cassatt', 'The Yellow Meads of Asphodel', 'Marks, Marks and Marks', 'Computer & Network Security', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('El Greco', 'The Other Side of Silence', 'Kris and Sons', 'Translation and Localization', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Dali', 'In a Glass Darkly', 'Treutel, Treutel and Treutel', 'Military', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Rothko', 'Dance Dance Dance', 'MacGyver Group', 'Automotive', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Gauguin', 'The Other Side of Silence', 'Kertzmann, Kertzmann and Kertzmann', 'Mechanical or Industrial Engineering', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Warhol', 'In Death Ground', 'Carter, Carter and Carter', 'Textiles', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Pissarro', 'The Violent Bear It Away', 'Becker Inc', 'Information Services', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Escher', 'Fear and Trembling', 'Keeling Group', 'Aviation & Aerospace', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Rubens', 'Eyeless in Gaza', 'Collier LLC', 'Semiconductors', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Raphael', 'Those Barren Leaves, Thrones, Dominations', 'Trantow-Trantow', 'Mechanical or Industrial Engineering', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Rothko', 'Jesting Pilate', 'Cummings-Cummings', 'Electrical / Electronic Manufacturing', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Durer', 'For a Breath I Tarry', 'Daugherty Inc', 'Think Tanks', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Ansel Adams', 'The Moving Toyshop', 'Stanton LLC', 'Medical Practice', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Bernini', 'Behold the Man', 'Hickle-Hickle', 'Higher Education', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Klimt', 'Pale Kings and Princes', 'Aufderhar-Aufderhar', 'Think Tanks', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Pollock', 'Stranger in a Strange Land', 'Mohr LLC', 'Computer & Network Security', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Escher', 'The Green Bay Tree', 'Langosh Group', 'Plastics', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Monet', 'Bury My Heart at Wounded Knee', 'Bashirian, Bashirian and Bashirian', 'Hospitality', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Caravaggio', 'The Mermaids Singing', 'Goodwin, Goodwin and Goodwin', 'Information Technology and Services', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Pissarro', 'Of Mice and Men', 'Ratke, Ratke and Ratke', 'Dairy', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Kahlo', 'A Handful of Dust', 'Mosciski, Mosciski and Mosciski', 'Farming', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Winslow Homer', 'The Golden Apples of the Sun', 'Schoen and Sons', 'Nonprofit Organization Management', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Raphael', 'Ego Dominus Tuus', 'Renner, Renner and Renner', 'Health, Wellness and Fitness', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Pissarro', 'A Handful of Dust', 'Lueilwitz, Lueilwitz and Lueilwitz', 'Individual & Family Services', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Klimt', 'Time of our Darkness', 'Lynch, Lynch and Lynch', 'Environmental Services', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Winslow Homer', 'The Way of All Flesh', 'Grant and Sons', 'Capital Markets', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Klimt', 'Edna OBrien', 'McGlynn-McGlynn', 'Wholesale', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Cassatt', 'A Summer Bird-Cage', 'Mann-Mann', 'Investment Banking', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Rembrandt', 'To Sail Beyond the Sunset', 'Pollich and Sons', 'Food Production', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Cezanne', 'Terrible Swift Sword', 'Heidenreich, Heidenreich and Heidenreich', 'Consumer Services', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Manet', 'Waiting for the Barbarians', 'Brakus Group', 'Real Estate', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Diego Rivera', 'For Whom the Bell Tolls', 'Kertzmann LLC', 'Machinery', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Vettriano', 'The Wings of the Dove', 'Erdman and Sons', 'Higher Education', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Warhol', 'The Green Bay Tree', 'Kirlin, Kirlin and Kirlin', 'Computer Software', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Raphael', 'Specimen Days', 'Lakin-Lakin', 'Individual & Family Services', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Da Vinci', 'A Summer Bird-Cage', 'Strosin Group', 'Glass, Ceramics & Concrete', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Pissarro', 'The Golden Apples of the Sun', 'Ruecker and Sons', 'Dairy', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Raphael', 'Mother Night', 'Stiedemann Group', 'International Trade and Development', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Kahlo', 'Mother Night', 'Monahan-Monahan', 'Industrial Automation', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Degas', 'To Say Nothing of the Dog', 'Schaden, Schaden and Schaden', 'Health, Wellness and Fitness', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Botticelli', 'From Here to Eternity', 'Price-Price', 'Glass, Ceramics & Concrete', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Diego Rivera', 'Tender Is the Night', 'Balistreri, Balistreri and Balistreri', 'Mechanical or Industrial Engineering', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Kandinsky', 'Dance Dance Dance', 'Jerde-Jerde', 'Restaurants', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Pollock', 'Moab Is My Washpot', 'Mertz, Mertz and Mertz', 'Think Tanks', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Manet', 'Antic Hay', 'Kemmer-Kemmer', 'Dairy', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Ansel Adams', 'The Doors of Perception', 'Boehm Inc', 'Farming', now(), 0.9008139930122572);
INSERT INTO employees (firstname, lastname, POSITION, office, start_date, salary) VALUES('Vettriano', 'The Other Side of Silence', 'Metz-Metz', 'Newspapers', now(), 0.9008139930122572);
